var BrowserData = function(){
    var mainObject = this;
    this.svg = {
        svg:"SVGElement" in window,
        svgInSvg:"SVGSVGElement" in window,
        rect:"SVGRect" in window,
        a:"SVGAElement" in window,
        angle:"SVGAngle" in window,
        animation:"SVGAnimationElement" in window,
        animate:"SVGAnimateElement" in window,
        animatedAngle:"SVGAnimatedAngle" in window,
        animatedBoolean:"SVGAnimatedBoolean" in window,
        animatedEnumeration:"SVGAnimatedEnumeration" in window,
        animatedInteger:"SVGAnimatedInteger" in window,
        animatedLength:"SVGAnimatedLength" in window,
        animatedLengthList:"SVGAnimatedLengthList" in window,
        animatedNumber:"SVGAnimatedNumber" in window,
        animatedNumberList:"SVGAnimatedNumberList" in window,
        animatedPreserveAspectRatio:"SVGAnimatedPreserveAspectRatio" in window,
        animatedRect:"SVGAnimatedRect" in window,
        animatedString:"SVGAnimatedString" in window,
        animatedTransformList:"SVGAnimatedTransformList" in window,
        animateMotion:"SVGAnimateMotionElement" in window,
        animateTransform:"SVGAnimateTransformElement" in window,
        circle:"SVGCircleElement" in window,
        clipPath:"SVGClipPathElement" in window,
        defs:"SVGDefsElement" in window,
        desc:"SVGDescElement" in window,
        ellipse:"SVGEllipseElement" in window,
        feBlend:"SVGFEBlendElement" in window,
        feColorMatrix:"SVGFEColorMatrixElement"in window,
        feComponentTransfer:"SVGFEComponentTransferElement" in window,
        feComposite:"SVGFECompositeElement" in window,
        feConvolveMatrix:"SVGFEConvolveMatrixElement" in window,
        feDiffuseLighting:"SVGFEDiffuseLightingElement" in window,
        feDisplacementMap:"SVGFEDisplacementMapElement" in window,
        feFlood:"SVGFEFloodElement" in window,
        feFuncA:"SVGFEFuncAElement" in window,
        feFuncB:"SVGFEFuncBElement" in window,
        feFuncG:"SVGFEFuncGElement" in window,
        feFuncR:"SVGFEFuncRElement" in window,
        feGaussianBlur:"SVGFEGaussianBlurElement" in window,
        feDistantLight:"SVGFEDistantLightElement" in window,
        feDropShadow:"SVGFEDropShadowElement" in window,
        feImage:"SVGFEImageElement" in window,
        feMerge:"SVGFEMergeElement" in window,
        feMergeNode:"SVGFEMergeNodeElement" in window,
        feMorphology:"SVGFEMorphologyElement" in window,
        feOffset:"SVGFEOffsetElement" in window,
        fePointLight:"SVGFEPointLightElement" in window,
        feSpecularLighting:"SVGFESpecularLightingElement" in window,
        feSpotLight:"SVGFESpotLightElement" in window,
        feTile:"SVGFETileElement" in window,
        feTurbulence:"SVGFETurbulenceElement" in window,
        filter:"SVGFilterElement" in window,
        foreignObject:"SVGForeignObjectElement" in window,
        g:"SVGGElement" in window,
        image:"SVGImageElement" in window,
        line:"SVGLineElement" in window,
        linearGradient:"SVGLinearGradientElement" in window,
        marker:"SVGMarkerElement" in window,
        mask:"SVGMaskElement" in window,
        metaData:"SVGMetadataElement" in window,
        mPath:"SVGMPathElement" in window,
        path:"SVGPathElement" in window,
        pattern:"SVGPatternElement" in window,
        polygon:"SVGPolygonElement" in window,
        polyLine:"SVGPolylineElement" in window,
        radialGradient:"SVGRadialGradientElement" in window,
        script:"SVGScriptElement" in window,
        style:"SVGStyleElement" in window,
        set:"SVGSetElement" in window,
        stop:"SVGStopElement" in window,
        switch:"SVGSwitchElement" in window,
        symbol:"SVGSymbolElement" in window,
        text:"SVGTextElement" in window,
        textPath:"SVGTextPathElement" in window,
        title:"SVGTitleElement" in window,
        tSpan:"SVGTSpanElement" in window,
        use:"SVGUseElement" in window,
        view:"SVGViewElement" in window,
    }
    this.html = {
        a:!(document.createElement("a") instanceof HTMLUnknownElement),
        abbr:!(document.createElement("abbr") instanceof HTMLUnknownElement),
        acronym:!(document.createElement("acronym") instanceof HTMLUnknownElement),
        address:!(document.createElement("address") instanceof HTMLUnknownElement),
        applet:!(document.createElement("applet") instanceof HTMLUnknownElement),
        area:!(document.createElement("area") instanceof HTMLUnknownElement),
        article:!(document.createElement("article") instanceof HTMLUnknownElement),
        aside:!(document.createElement("aside") instanceof HTMLUnknownElement),
        audio:!(document.createElement("audio") instanceof HTMLUnknownElement),
        b:!(document.createElement("b") instanceof HTMLUnknownElement),
        base:!(document.createElement("base") instanceof HTMLUnknownElement),
        bdi:!(document.createElement("bdi") instanceof HTMLUnknownElement),
        bdo:!(document.createElement("bdo") instanceof HTMLUnknownElement),
        bgsound:!(document.createElement("bgsound") instanceof HTMLUnknownElement),
        big:!(document.createElement("big") instanceof HTMLUnknownElement),
        blink:!(document.createElement("blink") instanceof HTMLUnknownElement),
        blockquote:!(document.createElement("blockquote") instanceof HTMLUnknownElement),
        body:!(document.createElement("body") instanceof HTMLUnknownElement),
        br:!(document.createElement("br") instanceof HTMLUnknownElement),
        button:!(document.createElement("button") instanceof HTMLUnknownElement),
        canvas:!(document.createElement("canvas") instanceof HTMLUnknownElement),
        caption:!(document.createElement("caption") instanceof HTMLUnknownElement),
        center:!(document.createElement("center") instanceof HTMLUnknownElement),
        cite:!(document.createElement("cite") instanceof HTMLUnknownElement),
        code:!(document.createElement("code") instanceof HTMLUnknownElement),
        col:!(document.createElement("col") instanceof HTMLUnknownElement),
        colgroup:!(document.createElement("colgroup") instanceof HTMLUnknownElement),
        content:!(document.createElement("content") instanceof HTMLUnknownElement),
        data:!(document.createElement("data") instanceof HTMLUnknownElement),
        datalist:!(document.createElement("datalist") instanceof HTMLUnknownElement),
        dd:!(document.createElement("dd") instanceof HTMLUnknownElement),
        del:!(document.createElement("del") instanceof HTMLUnknownElement),
        details:!(document.createElement("details") instanceof HTMLUnknownElement),
        dfn:!(document.createElement("dfn") instanceof HTMLUnknownElement),
        dialog:!(document.createElement("dialog") instanceof HTMLUnknownElement),
        dir:!(document.createElement("dir") instanceof HTMLUnknownElement),
        div:!(document.createElement("div") instanceof HTMLUnknownElement),
        dl:!(document.createElement("dl") instanceof HTMLUnknownElement),
        dt:!(document.createElement("dt") instanceof HTMLUnknownElement),
        em:!(document.createElement("em") instanceof HTMLUnknownElement),
        embed:!(document.createElement("embed") instanceof HTMLUnknownElement),
        fieldset:!(document.createElement("fieldset") instanceof HTMLUnknownElement),
        figcaption:!(document.createElement("figcaption") instanceof HTMLUnknownElement),
        figure:!(document.createElement("figure") instanceof HTMLUnknownElement),
        footer:!(document.createElement("footer") instanceof HTMLUnknownElement),
        form:!(document.createElement("form") instanceof HTMLUnknownElement),
        fieldset:!(document.createElement("fieldset") instanceof HTMLUnknownElement),
        frame:!(document.createElement("frame") instanceof HTMLUnknownElement),
        frameset:!(document.createElement("frameset") instanceof HTMLUnknownElement),
        h1:!(document.createElement("h1") instanceof HTMLUnknownElement),
        h2:!(document.createElement("h2") instanceof HTMLUnknownElement),
        h3:!(document.createElement("h3") instanceof HTMLUnknownElement),
        h4:!(document.createElement("h4") instanceof HTMLUnknownElement),
        h5:!(document.createElement("h5") instanceof HTMLUnknownElement),
        h6:!(document.createElement("h6") instanceof HTMLUnknownElement),
        head:!(document.createElement("head") instanceof HTMLUnknownElement),
        header:!(document.createElement("header") instanceof HTMLUnknownElement),
        hgroup:!(document.createElement("hgroup") instanceof HTMLUnknownElement),
        hr:!(document.createElement("hr") instanceof HTMLUnknownElement),
        html:!(document.createElement("html") instanceof HTMLUnknownElement),
        i:!(document.createElement("i") instanceof HTMLUnknownElement),
        iframe:!(document.createElement("fieldset") instanceof HTMLUnknownElement),
        image:!(document.createElement("image") instanceof HTMLUnknownElement),
        img:!(document.createElement("img") instanceof HTMLUnknownElement),
        input:!(document.createElement("input") instanceof HTMLUnknownElement),
        ins:!(document.createElement("ins") instanceof HTMLUnknownElement),
        kbd:!(document.createElement("kbd") instanceof HTMLUnknownElement),
        keygen:!(document.createElement("keygen") instanceof HTMLUnknownElement),
        label:!(document.createElement("label") instanceof HTMLUnknownElement),
        legend:!(document.createElement("legend") instanceof HTMLUnknownElement),
        li:!(document.createElement("li") instanceof HTMLUnknownElement),
        link:!(document.createElement("link") instanceof HTMLUnknownElement),
        main:!(document.createElement("main") instanceof HTMLUnknownElement),
        map:!(document.createElement("map") instanceof HTMLUnknownElement),
        mark:!(document.createElement("mark") instanceof HTMLUnknownElement),
        marquee:!(document.createElement("marquee") instanceof HTMLUnknownElement),
        menu:!(document.createElement("menu") instanceof HTMLUnknownElement),
        menuitem:!(document.createElement("menuitem") instanceof HTMLUnknownElement),
        meta:!(document.createElement("meta") instanceof HTMLUnknownElement),
        meter:!(document.createElement("meter") instanceof HTMLUnknownElement),
        nav:!(document.createElement("nav") instanceof HTMLUnknownElement),
        nobr:!(document.createElement("nober") instanceof HTMLUnknownElement),
        noembed:!(document.createElement("noembed") instanceof HTMLUnknownElement),
        noframes:!(document.createElement("noframes") instanceof HTMLUnknownElement),
        noscript:!(document.createElement("noscript") instanceof HTMLUnknownElement),
        object:!(document.createElement("object") instanceof HTMLUnknownElement),
        ol:!(document.createElement("ol") instanceof HTMLUnknownElement),
        optgroup:!(document.createElement("optgroup") instanceof HTMLUnknownElement),
        option:!(document.createElement("option") instanceof HTMLUnknownElement),
        output:!(document.createElement("output") instanceof HTMLUnknownElement),
        p:!(document.createElement("p") instanceof HTMLUnknownElement),
        param:!(document.createElement("param") instanceof HTMLUnknownElement),
        picture:!(document.createElement("picture") instanceof HTMLUnknownElement),
        plaintext:!(document.createElement("plaintext") instanceof HTMLUnknownElement),
        portal:!(document.createElement("portal") instanceof HTMLUnknownElement),
        pre:!(document.createElement("pre") instanceof HTMLUnknownElement),
        progress:!(document.createElement("progress") instanceof HTMLUnknownElement),
        q:!(document.createElement("q") instanceof HTMLUnknownElement),
        rb:!(document.createElement("rb") instanceof HTMLUnknownElement),
        rp:!(document.createElement("rp") instanceof HTMLUnknownElement),
        rt:!(document.createElement("rt") instanceof HTMLUnknownElement),
        rtc:!(document.createElement("rtc") instanceof HTMLUnknownElement),
        ruby:!(document.createElement("ruby") instanceof HTMLUnknownElement),
        s:!(document.createElement("s") instanceof HTMLUnknownElement),
        samp:!(document.createElement("samp") instanceof HTMLUnknownElement),
        script:!(document.createElement("script") instanceof HTMLUnknownElement),
        section:!(document.createElement("section") instanceof HTMLUnknownElement),
        select:!(document.createElement("select") instanceof HTMLUnknownElement),
        shadow:!(document.createElement("shadow") instanceof HTMLUnknownElement),
        slot:!(document.createElement("slot") instanceof HTMLUnknownElement),
        small:!(document.createElement("small") instanceof HTMLUnknownElement),
        source:!(document.createElement("source") instanceof HTMLUnknownElement),
        spacer:!(document.createElement("spacer") instanceof HTMLUnknownElement),
        span:!(document.createElement("span") instanceof HTMLUnknownElement),
        strike:!(document.createElement("strike") instanceof HTMLUnknownElement),
        strong:!(document.createElement("strong") instanceof HTMLUnknownElement),
        style:!(document.createElement("style") instanceof HTMLUnknownElement),
        sub:!(document.createElement("sub") instanceof HTMLUnknownElement),
        summary:!(document.createElement("summary") instanceof HTMLUnknownElement),
        sup:!(document.createElement("sup") instanceof HTMLUnknownElement),
        svg:"SVGElement" in window,
        table:!(document.createElement("table") instanceof HTMLUnknownElement),
        tbody:!(document.createElement("tbody") instanceof HTMLUnknownElement),
        td:!(document.createElement("td") instanceof HTMLUnknownElement),
        template:!(document.createElement("template") instanceof HTMLUnknownElement),
        textarea:!(document.createElement("textarea") instanceof HTMLUnknownElement),
        tfoot:!(document.createElement("tfoot") instanceof HTMLUnknownElement),
        th:!(document.createElement("th") instanceof HTMLUnknownElement),
        thead:!(document.createElement("fieldset") instanceof HTMLUnknownElement),
        time:!(document.createElement("time") instanceof HTMLUnknownElement),
        title:!(document.createElement("title") instanceof HTMLUnknownElement),
        tr:!(document.createElement("tr") instanceof HTMLUnknownElement),
        track:!(document.createElement("track") instanceof HTMLUnknownElement),
        tt:!(document.createElement("tt") instanceof HTMLUnknownElement),
        u:!(document.createElement("u") instanceof HTMLUnknownElement),
        ul:!(document.createElement("ul") instanceof HTMLUnknownElement),
        var:!(document.createElement("var") instanceof HTMLUnknownElement),
        video:!(document.createElement("video") instanceof HTMLUnknownElement),
        wbr:!(document.createElement("wbr") instanceof HTMLUnknownElement),
        xmp:!(document.createElement("xmp") instanceof HTMLUnknownElement),
    }
    this.css = {
        lineClamp:CSS.supports("-webkit-line-clamp","10"),
        textFillColor:CSS.supports("-webkit-text-fill-color","#000000"),
        textStroke:CSS.supports("-webkit-text-stroke","0"),
        textStrokeColor:CSS.supports("-webkit-text-stroke-color","#000000"),
        textStrokeWidth:CSS.supports("-webkit-text-stroke-width","0px"),
        accentColor:CSS.supports("accent-color","#000000"),
        alignContent:CSS.supports("align-content","initial"),
        alignItems:CSS.supports("align-items","initial"),
        alignSelf:CSS.supports("align-self","initial"),
        alignTracks:CSS.supports("align-tracks","initial"),
        all:CSS.supports("all","initial"),
        animation:CSS.supports("animation","initial"),
        animationComposition:CSS.supports("animation-composition","initial"),
        animationDelay:CSS.supports("animation-delay","initial"),
        animationDirection:CSS.supports("animation-direction","initial"),
        animationDuration:CSS.supports("animation-duration","initial"),
        animationFillMode:CSS.supports("animation-fill-mode","initial"),
        animationIterationCount:CSS.supports("animation-iteration-count","initial"),
        animationName:CSS.supports("animation-name","initial"),
        animationPlayState:CSS.supports("animation-play-state","initial"),
        animationTimeline:CSS.supports("animation-timeline","initial"),
        animationTimingFunction:CSS.supports("animation-timing-function","initial"),
        appearance:CSS.supports("appearance","initial"),
        aspectRatio:CSS.supports("aspect-ratio","initial"),
        backdropFilter:CSS.supports("backdrop-filter","initial"),
        backfaceVisibility:CSS.supports("backface-visibility","initial"),
        background:CSS.supports("background","initial"),
        backgroundAttachment:CSS.supports("background-attachment","initial"),
        backgroundBlendMode:CSS.supports("background-blend-mode","initial"),
        backgroundClip:CSS.supports("background-clip","initial"),
        backgroundColor:CSS.supports("background-color","initial"),
        backgroundImage:CSS.supports("background-image","initial"),
        backgroundOrigin:CSS.supports("background-origin","initial"),
        backgroundPosition:CSS.supports("background-position","initial"),
        backgroundPositionX:CSS.supports("background-position-x","initial"),
        backgroundPositionY:CSS.supports("background-position-y","initial"),
        backgroundRepeat:CSS.supports("background-repeat","initial"),
        backgroundSize:CSS.supports("background-size","initial"),
        blockSize:CSS.supports("block-size","initial"),
        border:CSS.supports("border","initial"),
        borderBlock:CSS.supports("border-block","initial"),
        borderBlockColor:CSS.supports("border-block-color","initial"),
        borderBlockEnd:CSS.supports("border-block-end","initial"),
        borderBlockEndColor:CSS.supports("border-block-end-color","initial"),
        borderBlockEndStyle:CSS.supports("border-block-end-style","initial"),
        borderBlockEndWidth:CSS.supports("border-block-end-width","initial"),
        borderBlockStart:CSS.supports("border-block-start","initial"),
        borderBlockStartColor:CSS.supports("border-block-start-color","initial"),
        borderBlockStartStyle:CSS.supports("border-block-start-style","initial"),
        borderBlockStartWidth:CSS.supports("border-block-start-width","initial"),
        borderBlockStyle:CSS.supports("border-block-style","initial"),
        borderBlockWidth:CSS.supports("border-block-width","initial"),
        borderBottom:CSS.supports("border-bottom","initial"),
        borderBottomColor:CSS.supports("border-bottom-color","initial"),
        borderBottomLeftRadius:CSS.supports("border-bottom-left-radius","initial"),
        borderBottomRightRadius:CSS.supports("border-bottom-right-radius","initial"),
        borderBottomStyle:CSS.supports("border-bottom-style","initial"),
        borderBottomWidth:CSS.supports("border-bottom-width","initial"),
        borderCollapse:CSS.supports("border-collapse","initial"),
        borderColor:CSS.supports("border-color","initial"),
        borderEndEndRadius:CSS.supports("border-end-end-radius","initial"),
        borderEndStartRadius:CSS.supports("border-bottom","initial"),
        borderImage:CSS.supports("border-image","initial"),
        borderImageOutset:CSS.supports("border-image-outset","initial"),
        borderImageRepeat:CSS.supports("border-color","initial"),
        borderImageSlice:CSS.supports("border-image-slice","initial"),
        borderImageSource:CSS.supports("border-image-source","initial"),
        borderImageWidth:CSS.supports("border-image-width","initial"),
        borderInline:CSS.supports("border-inline","initial"),
        borderInlineColor:CSS.supports("border-inline-color","initial"),
        borderInlineEnd:CSS.supports("border-inline-end","initial"),
        borderInlineEndColor:CSS.supports("border-inline-end-color","initial"),
        borderInlineEndStyle:CSS.supports("border-inline-end-style","initial"),
        borderInlineEndWidth:CSS.supports("border-inline-end-width","initial"),
        borderInlineStart:CSS.supports("border-inline-start","initial"),
        borderInlineStartColor:CSS.supports("border-inline-start-color","initial"),
        borderInlineStartStyle:CSS.supports("border-inline-start-style","initial"),
        borderInlineStartWidth:CSS.supports("border-inline-start-width","initial"),
        borderInlineStyle:CSS.supports("border-inline-style","initial"),
        borderInlineWidth:CSS.supports("border-inline-width","initial"),
        borderLeft:CSS.supports("border-left","initial"),
        borderLeftColor:CSS.supports("border-left-color","initial"),
        borderLeftStyle:CSS.supports("border-left-style","initial"),
        borderLeftWidth:CSS.supports("border-left-width","initial"),
        borderRadius:CSS.supports("border-radius","initial"),
        borderRight:CSS.supports("border-left","initial"),
        borderRightColor:CSS.supports("border-right-color","initial"),
        borderRightStyle:CSS.supports("border-right-style","initial"),
        borderRightWidth:CSS.supports("border-right-width","initial"),
        borderSpacing:CSS.supports("border-spacing","initial"),
        borderStartEndRadius:CSS.supports("border-start-end-radius","initial"),
        borderStartStartRadius:CSS.supports("border-start-start-radius","initial"),
        borderStyle:CSS.supports("border-style","initial"),
        borderTop:CSS.supports("border-top","initial"),
        borderTopColor:CSS.supports("border-top-color","initial"),
        borderTopLeftRadius:CSS.supports("border-top-left-radius","initial"),
        borderTopRightRadius:CSS.supports("border-top-right-radius","initial"),
        borderTopWidth:CSS.supports("border-top-width","initial"),
        borderTopStyle:CSS.supports("border-top-style","initial"),
        borderWidth:CSS.supports("border-width","initial"),
        bottom:CSS.supports("bottom","initial"),
        boxDecorationBreak:CSS.supports("box-decoration-break","initial"),
        boxShadow:CSS.supports("box-shadow","initial"),
        boxSizing:CSS.supports("box-sizing","initial"),
        breakAfter:CSS.supports("break-after","initial"),
        breakBefore:CSS.supports("break-before","initial"),
        breakInside:CSS.supports("break-inside","initial"),
        captionSide:CSS.supports("caption-side","initial"),
        caretColor:CSS.supports("caret-color","initial"),
        clear:CSS.supports("clear","initial"),
        clip:CSS.supports("clip","initial"),
        clipPath:CSS.supports("clip-path","initial"),
        color:CSS.supports("color","initial"),
        color:CSS.supports("color","initial"),
        columnCount:CSS.supports("column-count","initial"),
        columnFill:CSS.supports("column-fill","initial"),
        columnGap:CSS.supports("column-gap","initial"),
        columnRule:CSS.supports("column-rule","initial"),
        columnRuleStyle:CSS.supports("column-rule-style","initial"),
        columnRuleWidth:CSS.supports("column-rule-width","initial"),
        columnRuleColor:CSS.supports("column-rule-color","initial"),
        columnSpan:CSS.supports("column-span","initial"),
        columnWidth:CSS.supports("column-width","initial"),
        columns:CSS.supports("columns","initial"),
        contain:CSS.supports("contain","initial"),
        containIntrinsicBlockSize:CSS.supports("contain-intrinsic-block-size","initial"),
        containIntrinsicHeight:CSS.supports("contain-intrinsic-height","initial"),
        containIntrinsicInlineSize:CSS.supports("contain-intrinsic-inline-size","initial"),
        containIntrinsicSize:CSS.supports("contain-intrinsic-size","initial"),
        containIntrinsicWidth:CSS.supports("contain-intrinsic-width","initial"),
        container:CSS.supports("container","initial"),
        containerName:CSS.supports("container-name","initial"),
        containerType:CSS.supports("container-type","initial"),
        content:CSS.supports("content","initial"),
        contentVisibility:CSS.supports("content-visibility","initial"),
        counterIncrement:CSS.supports("counter-increment","initial"),
        counterReset:CSS.supports("counter-reset","initial"),
        counterSet:CSS.supports("counter-set","initial"),
        cursor:CSS.supports("cursor","initial"),
        direction:CSS.supports("direction","initial"),
        display:CSS.supports("display","initial"),
        emptyCells:CSS.supports("empty-cells","initial"),
        filter:CSS.supports("filter","initial"),
        flex:CSS.supports("flex","initial"),
        flexBasis:CSS.supports("flex-basis","initial"),
        flexDirection:CSS.supports("flex-direction","initial"),
        flexFlow:CSS.supports("flex-flow","initial"),
        flexGrow:CSS.supports("flex-grow","initial"),
        flexShrink:CSS.supports("flex-shrink","initial"),
        flexWrap:CSS.supports("flex-wrap","initial"),
        float:CSS.supports("float","initial"),
        font:CSS.supports("font","initial"),
        fontFamily:CSS.supports("font-family","initial"),
        fontFeatureSettings:CSS.supports("font-feature-settings","initial"),
        fontKerning:CSS.supports("font-kerning","initial"),
        fontLanguageOverride:CSS.supports("font-language-override","initial"),
        fontOpticalSizing:CSS.supports("font-optical-sizing","initial"),
        fontPallete:CSS.supports("font-pallete","initial"),
        fontSize:CSS.supports("font-size","initial"),
        fontSizeAdjust:CSS.supports("font-size-adjust","initial"),
        fontStretch:CSS.supports("font-stretch","initial"),
        fontStyle:CSS.supports("font-style","initial"),
        fontSyntesis:CSS.supports("font-syntesis","initial"),
        fontVariant:CSS.supports("font-variant","initial"),
        fontVariantAlternates:CSS.supports("font-variant-alternates","initial"),
        fontVariantCaps:CSS.supports("font-variant-caps","initial"),
        fontVariantEastAsian:CSS.supports("font-variant-east-asian","initial"),
        fontVariantEmoji:CSS.supports("font-variant-emoji","initial"),
        fontVariantLigatures:CSS.supports("font-variant-ligatures","initial"),
        fontVariantNumeric:CSS.supports("font-variant-numeric","initial"),
        fontVariantPosition:CSS.supports("font-variant-position","initial"),
        fontVariantionSettings:CSS.supports("font-variantion-settings","initial"),
        fontWeight:CSS.supports("font-weight","initial"),
        forcedColorAdjust:CSS.supports("forced-color-adjust","initial"),
        gap:CSS.supports("gap","initial"),
        grid:CSS.supports("grid","initial"),
        gridArea:CSS.supports("grid-area","initial"),
        gridAutoColumns:CSS.supports("grid-auto-columns","initial"),
        gridAutoFlow:CSS.supports("grid-auto-flow","initial"),
        gridAutoColumns:CSS.supports("grid-auto-columns","initial"),
        gridColumn:CSS.supports("grid-column","initial"),
        gridColumnStart:CSS.supports("grid-column-start","initial"),
        gridColumnEnd:CSS.supports("grid-column-end","initial"),
        gridRow:CSS.supports("grid-row","initial"),
        gridRowStart:CSS.supports("grid-row-start","initial"),
        gridRowEnd:CSS.supports("grid-row-end","initial"),
        gridTemplate:CSS.supports("grid-template","initial"),
        gridTemplateAreas:CSS.supports("grid-template-areas","initial"),
        gridTemplateColumns:CSS.supports("grid-template-columns","initial"),
        gridTemplateRows:CSS.supports("grid-template-rows","initial"),
        hangingPunctuation:CSS.supports("hanging-punctuation","initial"),
        height:CSS.supports("height","initial"),
        hyphenateCharacter:CSS.supports("hyphenate-character","initial"),
        hyphenateLimitChars:CSS.supports("hyphenate-limit-chars","initial"),
        hyphens:CSS.supports("hyphens","initial"),
        imageOrientation:CSS.supports("image-orientation","initial"),
        imageRendering:CSS.supports("image-rendering","initial"),
        imageResolution:CSS.supports("image-resolution","initial"),
        imeMode:CSS.supports("ime-mode","initial"),
        initialLetter:CSS.supports("initial-letter","initial"),
        initialLetterAlign:CSS.supports("initial-letter-align","initial"),
        inlineSize:CSS.supports("inline-size","initial"),
        inset:CSS.supports("inset","initial"),
        insetBlock:CSS.supports("inset-block","initial"),
        insetBlockEnd:CSS.supports("inset-block-end","initial"),
        insetBlockStart:CSS.supports("inset-block-start","initial"),
        insetInline:CSS.supports("inset-inline","initial"),
        insetInlineEnd:CSS.supports("inset-inline-end","initial"),
        insetInlineStart:CSS.supports("inset-inline-start","initial"),
        isolation:CSS.supports("isolation","initial"),
        justifyContent:CSS.supports("justify-content","initial"),
        justifyItems:CSS.supports("justify-items","initial"),
        justifySelf:CSS.supports("justify-self","initial"),
        justifyTracks:CSS.supports("justify-tracks","initial"),
        left:CSS.supports("left","initial"),
        letterSpacing:CSS.supports("letter-spacing","initial"),
        lineBreak:CSS.supports("line-break","initial"),
        lineHeight:CSS.supports("line-height","initial"),
        lineHeightStep:CSS.supports("line-height-step","initial"),
        listStyle:CSS.supports("list-style","initial"),
        listStyleImage:CSS.supports("list-style-image","initial"),
        listStylePosition:CSS.supports("list-style-position","initial"),
        listStyleType:CSS.supports("list-style-type","initial"),
        margin:CSS.supports("margin","initial"),
        marginTop:CSS.supports("margin-top","initial"),
        marginBottom:CSS.supports("margin-bottom","initial"),
        marginLeft:CSS.supports("margin-left","initial"),
        marginRight:CSS.supports("margin-right","initial"),
        marginTrim:CSS.supports("margin-trim","initial"),
        marginBlock:CSS.supports("margin-block","initial"),
        marginBlockStart:CSS.supports("margin-block-start","initial"),
        marginBlockEnd:CSS.supports("margin-block-end","initial"),
        marginInline:CSS.supports("margin-inline","initial"),
        marginInlineStart:CSS.supports("margin-inline-start","initial"),
        marginInlineEnd:CSS.supports("margin-inline-end","initial"),
        mask:CSS.supports("mask","initial"),
        maskBorder:CSS.supports("mask","initial"),
        maskBorderMode:CSS.supports("mask-border-mode","initial"),
        maskBorderOutset:CSS.supports("mask-border-outset","initial"),
        maskBorderRepeat:CSS.supports("mask-border-repeat","initial"),
        maskBorderSlice:CSS.supports("mask-border-slice","initial"),
        maskBorderSource:CSS.supports("mask-border-source","initial"),
        maskBorderWidth:CSS.supports("mask-border-width","initial"),
        maskClip:CSS.supports("mask-clip","initial"),
        maskComposite:CSS.supports("mask-composite","initial"),
        maskImage:CSS.supports("mask-image","initial"),
        maskMode:CSS.supports("mask-mode","initial"),
        maskOrigin:CSS.supports("mask-origin","initial"),
        maskPosition:CSS.supports("mask-position","initial"),
        maskRepeat:CSS.supports("mask-repeat","initial"),
        maskSize:CSS.supports("mask-size","initial"),
        maskType:CSS.supports("mask-type","initial"),
        mansoryAutoFlow:CSS.supports("mansory-auto-flow","initial"),
        mathDepth:CSS.supports("math-depth","initial"),
        mathShift:CSS.supports("math-shift","initial"),
        mathStyle:CSS.supports("math-style","initial"),
        maxBlockSize:CSS.supports("max-block-size","initial"),
        maxInlineSize:CSS.supports("max-inline-size","initial"),
        maxWidth:CSS.supports("max-width","initial"),
        maxHeight:CSS.supports("max-height","initial"),
        minBlockSize:CSS.supports("min-block-size","initial"),
        minInlineSize:CSS.supports("min-inline-size","initial"),
        minWidth:CSS.supports("min-width","initial"),
        minHeight:CSS.supports("min-height","initial"),
        mixBlendMode:CSS.supports("mix-blend-mode","initial"),
        objectFit:CSS.supports("object-fit","initial"),
        objectPosition:CSS.supports("object-position","initial"),
        offset:CSS.supports("offset","initial"),
        offsetAnchor:CSS.supports("offset-anchor","initial"),
        offsetDistance:CSS.supports("offset-distance","initial"),
        offsetPath:CSS.supports("offset-path","initial"),
        offsetPosition:CSS.supports("offset-position","initial"),
        offsetRotate:CSS.supports("offset-rotate","initial"),
        opacity:CSS.supports("opacity","initial"),
        order:CSS.supports("order","initial"),
        orphans:CSS.supports("orphans","initial"),
        outline:CSS.supports("outline","initial"),
        outlineColor:CSS.supports("outline-color","initial"),
        outlineOffset:CSS.supports("outline-offset","initial"),
        outlineStyle:CSS.supports("outline-style","initial"),
        outlineWidth:CSS.supports("outline-width","initial"),
        overflow:CSS.supports("overflow","initial"),
        overflowX:CSS.supports("overflow-x","initial"),
        overflowY:CSS.supports("overflow-y","initial"),
        overflowAnchor:CSS.supports("overflow-anchor","initial"),
        overflowBlock:CSS.supports("overflow-block","initial"),
        overflowClipMargin:CSS.supports("overflow-clip-margin","initial"),
        overflowInline:CSS.supports("overflow-inline","initial"),
        overflowWrap:CSS.supports("overflow-wrap","initial"),
        overscrollBehavior:CSS.supports("overscroll-behavior","initial"),
        overscrollBehaviorBlock:CSS.supports("overscroll-behavior-block","initial"),
        overscrollBehaviorInline:CSS.supports("overscroll-behavior-inline","initial"),
        overscrollBehaviorX:CSS.supports("overscroll-behavior-x","initial"),
        overscrollBehaviorY:CSS.supports("overscroll-behavior-y","initial"),
        padding:CSS.supports("padding","initial"),
        paddingTop:CSS.supports("padding-top","initial"),
        paddingBottom:CSS.supports("padding-bottom","initial"),
        paddingLeft:CSS.supports("padding-left","initial"),
        paddingRight:CSS.supports("padding-right","initial"),
        paddingBlock:CSS.supports("padding-block","initial"),
        paddingBlockStart:CSS.supports("padding-block-start","initial"),
        paddingBlockEnd:CSS.supports("padding-block-end","initial"),
        paddingInline:CSS.supports("padding-inline","initial"),
        paddingInlineStart:CSS.supports("padding-inline-start","initial"),
        paddingInlineEnd:CSS.supports("padding-inline-end","initial"),
        pageBreakAfter:CSS.supports("pageBreakAfter","initial"),
        pageBreakBefore:CSS.supports("pageBreakBefore","initial"),
        pageBreakInside:CSS.supports("pageBreakInside","initial"),
        paintOrder:CSS.supports("paint-order","initial"),
        perspective:CSS.supports("perspective","initial"),
        perspectiveOrigin:CSS.supports("perspective-origin","initial"),
        placeContent:CSS.supports("place-content","initial"),
        placeItems:CSS.supports("place-items","initial"),
        placeSelf:CSS.supports("place-self","initial"),
        pointerEvents:CSS.supports("pointer-events","initial"),
        position:CSS.supports("position","initial"),
        printColorAdjust:CSS.supports("printColorAdjust","initial"),
        quotes:CSS.supports("quotes","initial"),
        resize:CSS.supports("resize","initial"),
        right:CSS.supports("right","initial"),
        rotate:CSS.supports("rotate","initial"),
        rowGap:CSS.supports("row-gap","initial"),
        rubyAlign:CSS.supports("ruby-align","initial"),
        rubyPosition:CSS.supports("ruby-position","initial"),
        scale:CSS.supports("scale","initial"),
        scrollBehavior:CSS.supports("scroll-behavior","initial"),
        scrollMargin:CSS.supports("scroll-margin","initial"),
        scrollMarginBlock:CSS.supports("scroll-margin-block","initial"),
        scrollMarginBlockEnd:CSS.supports("scroll-margin-block-end","initial"),
        scrollMarginBlockStart:CSS.supports("scroll-margin-block-start","initial"),
        scrollMarginBottom:CSS.supports("scroll-margin-bottom","initial"),
        scrollMarginInline:CSS.supports("scroll-margin-inline","initial"),
        scrollMarginInlineEnd:CSS.supports("scroll-margin-inline-end","initial"),
        scrollMarginInlineStart:CSS.supports("scroll-margin-inline-start","initial"),
        scrollMarginLeft:CSS.supports("scroll-margin-left","initial"),
        scrollMarginRight:CSS.supports("scroll-margin-right","initial"),
        scrollMarginTop:CSS.supports("scroll-margin-top","initial"),
        scrollpadding:CSS.supports("scroll-padding","initial"),
        scrollpaddingBlock:CSS.supports("scroll-padding-block","initial"),
        scrollpaddingBlockEnd:CSS.supports("scroll-padding-block-end","initial"),
        scrollpaddingBlockStart:CSS.supports("scroll-padding-block-start","initial"),
        scrollpaddingBottom:CSS.supports("scroll-padding-bottom","initial"),
        scrollpaddingInline:CSS.supports("scroll-padding-inline","initial"),
        scrollpaddingInlineEnd:CSS.supports("scroll-padding-inline-end","initial"),
        scrollpaddingInlineStart:CSS.supports("scroll-padding-inline-start","initial"),
        scrollpaddingLeft:CSS.supports("scroll-padding-left","initial"),
        scrollpaddingRight:CSS.supports("scroll-padding-right","initial"),
        scrollpaddingTop:CSS.supports("scroll-padding-top","initial"),
        scrollSnapAlign:CSS.supports("scroll-snap-align","initial"),
        scrollSnapStop:CSS.supports("scroll-snap-stop","initial"),
        scrollSnapType:CSS.supports("scroll-snap-type","initial"),
        scrollTimeline:CSS.supports("scroll-timeline","initial"),
        scrollTimelineAxis:CSS.supports("scroll-timeline-axis","initial"),
        scrollTimelineName:CSS.supports("scroll-timeline-name","initial"),
        scrollbarColor:CSS.supports("scrollbar-color","initial"),
        scrollbarGutter:CSS.supports("scrollbar-gutter","initial"),
        scrollbarWidth:CSS.supports("scrollbar-width","initial"),
        shapeImageThreshold:CSS.supports("shape-image-threshold","initial"),
        shapeMargin:CSS.supports("shape-margin","initial"),
        shapeOutside:CSS.supports("shape-outside","initial"),
        tabSize:CSS.supports("tab-size","initial"),
        tableLayout:CSS.supports("table-layout","initial"),
        textAlign:CSS.supports("text-align","initial"),
        textAlignLast:CSS.supports("text-align-last","initial"),
        textCombineUpright:CSS.supports("text-combine-upright","initial"),
        textDecoration:CSS.supports("text-decoration","initial"),
        textDecorationColor:CSS.supports("text-decoration-color","initial"),
        textDecorationLine:CSS.supports("text-decoration-line","initial"),
        textDecorationSkip:CSS.supports("text-decoration-skip","initial"),
        textDecorationSkipInk:CSS.supports("text-decoration-skip-ink","initial"),
        textDecorationStyle:CSS.supports("text-decoration-style","initial"),
        textDecorationThickness:CSS.supports("text-decoration-thickness","initial"),
        textEmphasis:CSS.supports("text-emphasis","initial"),
        textEmphasisColor:CSS.supports("text-emphasis-color","initial"),
        textEmphasisPosition:CSS.supports("text-emphasis-position","initial"),
        textEmphasisStyle:CSS.supports("text-emphasis-style","initial"),
        textIndent:CSS.supports("text-indent","initial"),
        textJustify:CSS.supports("text-justify","initial"),
        textOrientation:CSS.supports("text-orientation","initial"),
        textOverflow:CSS.supports("text-overflow","initial"),
        textRendering:CSS.supports("text-rendering","initial"),
        textShadow:CSS.supports("text-shadow","initial"),
        textSizeAdjust:CSS.supports("text-size-adjust","initial"),
        textTransform:CSS.supports("text-transform","initial"),
        textUnderlineOffset:CSS.supports("text-underline-offset","initial"),
        textUnderlinePosition:CSS.supports("text-underline-position","initial"),
        top:CSS.supports("top","initial"),
        touchAction:CSS.supports("touch-action","initial"),
        transform:CSS.supports("transform","initial"),
        transformOrigin:CSS.supports("transform-origin","initial"),
        transformBox:CSS.supports("transform-box","initial"),
        transformStyle:CSS.supports("transform-style","initial"),
        transition:CSS.supports("transition","initial"),
        transitionDelay:CSS.supports("transition-delay","initial"),
        transitionDuration:CSS.supports("transition-duration","initial"),
        transitionProperty:CSS.supports("transition-property","initial"),
        transitionTimingFunction:CSS.supports("transition-timing-function","initial"),
        translate:CSS.supports("translate","initial"),
        unicodeBidi:CSS.supports("unicode-bidi","initial"),
        userSelect:CSS.supports("user-select","initial"),
        verticalAlign:CSS.supports("vertical-align","initial"),
        visibility:CSS.supports("visibility","initial"),
        whiteSpace:CSS.supports("white-space","initial"),
        widows:CSS.supports("widows","initial"),
        width:CSS.supports("width","initial"),
        willChange:CSS.supports("will-change","initial"),
        wordBreak:CSS.supports("word-break","initial"),
        wordSpacing:CSS.supports("word-spacing","initial"),
        writingMode:CSS.supports("writing-mode","initial"),
        zIndex:CSS.supports("z-index","initial"),
    }
    this.js = {
        localStorage:"localStorage" in window,
        sessionStorage:"sessionStorage" in window,
        cookies:navigator.cookieEnabled,
        indexedDB:"indexedDB" in window,
        webSQL:"openDatabase" in window,
        file:"File" in window,
        fileReader:"FileReader" in window,
        inputFileDirectory:"webkitdirectory" in document.createElement("input"),
        fileSystemAccess:"FileSystemHandle" in window,
        fileSystemEntry:"FileSystemEntry" in window,
        battery:navigator.getBattery() != undefined,
        bluetooth:"Bluetooth" in window,
        broadcastChannel:"BroadcastChannel" in window,
        barcodeDetector:"BarcodeDetector" in window,
        beacon:"sendBeacon" in navigator,
        backgroundFetch:"BackgroundFetchManager" in self,
        backgroundTasks:"requestIdleCallback" in window,
        fontFace:"FontFace" in window,
        cssPaint:"paintWorklet" in CSS,
        registerProperty:"registerProperty" in CSS,
        CSSom:"CSS" in window,
        canvas2D:"CanvasRenderingContext2D" in window,
        offscreenCanvas:"OffscreenCanvas" in window,
        messageChannel:"MessageChannel" in window,
        clipboard:"clipboard" in navigator,
        console:"console" in window,
        compressionStream:"CompressionStream" in window,
        contactPicker:"contacts" in navigator,
        deviceOrientation:"DeviceOrientationEvent" in window,
        encoding:"TextEncoder" in window,
        eyeDropper:"EyeDropper" in window,
        fetch:"fetch" in window,
        fullscreen:"requestFullscreen" in document.documentElement,
        gamepad:"getGamepads" in navigator,
        geolocation:"geolocation" in navigator,
        sanitizer:"Sanitizer" in window,
        history:"history" in window,
        idleDetector:"IdleDetector" in window,
        mediaDevices:"mediaDevices" in navigator,
        ink:"ink" in navigator,
        intersectionObserver:"IntersectionObserver" in window,
        keyboard:"keyboard" in navigator,
        localFont:"queryLocalFonts" in window,
        webGL:"WebGLRenderingContext" in window,
        webGPU:"gpu" in navigator,
        webAudio:"AudioContext" in window,
        layoutInstability:"LayoutShift" in window,
        mediaCapabilities:"mediaCapabilities" in navigator,
        mediaCaptureAndStreams:"MediaStream" in window,
        mediaSession:"mediaSession" in navigator,
        mediaSource:"MediaSource" in window,
        mediaStream:"MediaStream" in window,
        navigation:"Navigation" in window,
        networkInformation:"NetworkInformation" in window,
        pageVisibility:document.hidden != undefined || document.mozHidden != undefined || document.msHidden != undefined || document.webkitHidden != undefined,
        permissions:"Permissions" in window,
        scheduler:"Scheduler" in window,
        paymentManager:"PaymentManager" in window,
        paymentRequest:"PaymentRequest" in window,
        pictureInPicture:"PictureInPictureWindow" in window,
        pointerEvent:"PointerEvent" in window,
        proximityEvents:"onuserproximity" in window || "window.ondeviceproximity" in window,
        performance:"Performance" in window,
        pointerLock:"requestPointerLock" in document.createElement("canvas"),
        push:"PushManager" in window,
        periodicSyncManager:"PeriodicSyncManager" in window,
        presentation:"Presentation" in window,
        reporting:"ReportingObserver" in window,
        resizeObserver:"ResizeObserver" in window,
        screenCapture:"CaptureController" in window,
        sensor:"Sensor" in window,
        storageAccess:"requestStorageAccess" in document,
        screenOrientation:"ScreenOrientation" in window,
        serverSentEvent:"EventSource" in window,
        streams:"ReadableStream" in window,
        screenWakeLock:"WakeLock" in window,
        serviceWorker:"ServiceWorker" in window,
        selection:"Selection" in window,
        storage:"storage" in navigator,
        touchEvent:"TouchEvent" in window,
        trustedTypes:"TrustedHTML" in window,
        urlPattern:"URLPattern" in window,
        userAgentData:"userAgentData" in navigator,
        url:"URL" in window,
        vibration:"vibrate" in navigator,
        virtualKeyboard:"virtualKeyboard" in navigator,
        visualViewport:"visualViewport" in window,
        webAnimation:"Animation" in window,
        webShare:"share" in navigator,
        webRTC:"RTCDataChannel" in window,
        webSpeech:"speechSynthesis" in window,
        webTransport:"WebTransport" in window,
        webAuthentication:"Credential" in window,
        webStorage:"localStorage" in window && "sessionStorage" in window,
        webUSB:"USB" in window,
        webWorker:"Worker" in window,
        webVR:"getVRDisplays" in navigator,
        webCrypto:"Crypto" in window,
        webCodecs:"AudioDecoder" in window || "VideoDecoder" in window,
        webVVT:"VTTCue" in window,
        webLocks:"locks" in navigator,
        webXR:"xr" in navigator,
        webMIDI:"MIDIInputMap" in window,
        webHID:"HID" in window,
        webSocket:"WebSocket" in window,
        webNFC:"NDEFReader" in window,
        webOTP:"OTPCredential" in window,
        windowControlsOverlay:"WindowControlsOverlay" in window,
        webNotifications:"Notification" in window,
        XMLHttpRequest:"XMLHttpRequest" in window,
        setTimeout:"setTimeout" in window,
        setInterval:"setInterval" in window,
        Math:"Math" in window,
        object:"Object" in window,
        async:"Promise" in window,
    }
    this.score = {
        svg:[0,0],
        html:[0,0],
        css:[0,0],
        js:[0,0],
    }
    this.testers = ["html","css","js","svg"]
    for(var language of mainObject.testers){
        for(var key in mainObject[language]){
            if(mainObject[language][key] == true){
                mainObject.score[language][0]++;
            }
            mainObject.score[language][1]++;
        }
    }
    this.support = function(type,name,value){
        if(type == "css" ||type == "css01" ){
            return name in document.body.style;
        }else if(type == "css02"){
            return CSS.supports(name,value == undefined ? "initial" : value);
        }else if(type == "html"){
            return !(document.createElement(name) instanceof HTMLUnknownElement);
        }else if(type == "attribute"){
            return name in document.createElement(value);
        }else if(type == "svg"){
            return document.createElementNS("http://www.w3.org/2000/svg",name).toString() != "[object SVGElement]";
        }else if(type == "js" || type == "js01"){
            name = name.charAt(0).toUpperCase()+name.slice(1);
            var nameWithPrefix = window["moz"+name] || window["webkit"+name] || window["ms"+name] || window["shim"+name] || window[name] || undefined;
            return nameWithPrefix != undefined;
        }else if(type == "js02"){
            return window[name] != undefined;
        }
    }
}